import { APP_VERSION, rebuildProjection } from "./domain.js";
import { snapshot, clearAndRestore, getAll, put } from "./database.js";

async function digest(text) { const bytes = new TextEncoder().encode(text); const hash = await crypto.subtle.digest("SHA-256", bytes); return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,"0")).join(""); }
function stablePayload(data) { return JSON.stringify(data); }
export async function makeBackup(db) { const data = await snapshot(db); const checksum = await digest(stablePayload(data)); return { format:"mimi-backup", formatVersion:1, applicationVersion:APP_VERSION, exportedAt:new Date().toISOString(), checksum:{algorithm:"SHA-256",value:checksum}, data }; }
export async function downloadBackup(db, filename = `mimi-backup-${new Date().toISOString().slice(0,10)}.json`) { const backup=await makeBackup(db); const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:"application/json"})); const a=document.createElement("a");a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); return backup; }
export async function validateBackup(backup) { if (!backup || backup.format!=="mimi-backup" || backup.formatVersion!==1 || !backup.data) throw new Error("Not a supported Mimi backup."); const required=["profile","questDefinitions","events","completionClaims","rewardGrants","achievementUnlocks","titleUnlocks","projections","settings","audit"]; for(const key of required) if(!Array.isArray(backup.data[key])) throw new Error(`Backup is missing ${key}.`); const actual=await digest(stablePayload(backup.data)); if(backup.checksum?.value && actual!==backup.checksum.value) throw new Error("Backup checksum does not match."); const eventIds=new Set(backup.data.events.map(e=>e.id)); const questIds=new Set(backup.data.questDefinitions.map(q=>q.id)); if(eventIds.size!==backup.data.events.length || backup.data.events.some(e=>!e.id)) throw new Error("Backup contains invalid or duplicate event IDs."); if(backup.data.rewardGrants.some(g=>!g.id||!eventIds.has(g.eventId))) throw new Error("Backup contains a reward without an event."); if(backup.data.events.some(e=>e.questId && !questIds.has(e.questId))) throw new Error("Backup contains an event with an unknown quest."); if(backup.data.completionClaims.some(c=>!c.key||!eventIds.has(c.eventId))) throw new Error("Backup contains an invalid completion claim."); if(backup.data.profile.some(p=>!p.id)) throw new Error("Backup contains an invalid profile."); return true; }
export async function restoreBackup(db, backup) { await validateBackup(backup); const preImport=await makeBackup(db); await clearAndRestore(db,backup.data); const data={events:await getAll(db,"events"),grants:await getAll(db,"rewardGrants"),quests:await getAll(db,"questDefinitions"),achievements:await getAll(db,"achievementUnlocks")}; const projection=rebuildProjection(data); await put(db,"projections",{id:"current",...projection}); await put(db,"audit",{id:`audit_restore_${crypto.randomUUID()}`,type:"restore",at:new Date().toISOString(),sourceVersion:backup.applicationVersion}); return {preImport,projection}; }
